version: '3.8'

services:
  energy-ai:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    command: >
      sh -c "while true; do
        python3 /app/src/train_agent.py;
        python3 /app/src/test_agent.py;
        sleep 86400;  # Sleep for 24 hours
      done"
    deploy:
      restart_policy:
        condition: on-failure

  cron:
    image: appropriate/curl
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
    entrypoint: >
      sh -c "echo '0 14 * * * curl -o /app/data/electricity_prices.json http://your-iobroker-url/path-to-json' | crontab - && cron -f"